exports.DISTRICTS = [
  { code: 1, name: '서울' },
  { code: 3, name: '경기' },
  { code: 100, name: '인천' },
  { code: 101, name: '부산' },
  { code: 102, name: '대구' },
  { code: 103, name: '대전' },
  { code: 104, name: '울산' },
  { code: 105, name: '광주' },
  { code: 106, name: '세종' },
  { code: 107, name: '경북' },
  { code: 108, name: '경남' },
  { code: 109, name: '전북' },
  { code: 110, name: '전남' },
  { code: 111, name: '충북' },
  { code: 112, name: '충남' },
  { code: 113, name: '강원' },
  { code: 114, name: '제주' },
];
